### ISSUE TITLE
Time Zone Bug

### ISSUE THREAD

**Issue by marionbarker** [loopnlearn/LoopWorkspace#19]
**Describe the bug**
See this documentation for the description.
* https://www.loopandlearn.org/loop-time/#freeaps-timezone-bug

This is a long-time bug that required modifications in more than just the Loop repository.
We need to figure out how to fix this now that the loopnlearn repo has added more repositories to the .gitmodules file.

**Add this to the to-do list for the future FreeAPS release**

**Comment by bjornoleh** [comment]
Relevant commits related to the Time zone bug:

The bug was introduced with the addition of "Show required carbs in app badge":

https://github.com/ivalkou/Loop/commit/21396d3965c64d3fa93cf09718d2f8635d0c4703

The bug can now be avoided by turning off the settings toggle for "Show required carbs on the app badge", found in "Other FreeAPS settings". This partial fix was introduced here:

https://github.com/ivalkou/Loop/commit/a7547e17d1b8da697f9ffe95a2a5fed721e29f9d

**Comment by marionbarker** [comment]
This is fixed in released FreeAPS with the hotfix and merged into freeaps_dev branch for future releases.
* https://github.com/loopnlearn/LoopWorkspace/releases/tag/v2.2.204.tz_hotfix

**Comment by marionbarker** [comment]
The fix to the SettingsTableViewController.swift file will be in the next freeaps release.  It was added to the freeaps_dev branch with [commit 90b0c8c](https://github.com/loopnlearn/Loop/commit/90b0c8c5620bbd1977086792677c005ea4ce7317)
